<a href="https://colab.research.google.com/github/Karthikeyan-Analyst/pandas-practice/blob/Python_practice/pandas_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving obesity_dataset_2000_rows.csv to obesity_dataset_2000_rows.csv

In [2]:
import pandas as pd
obesity_data = pd.read_csv('obesity_dataset_2000_rows.csv')
obesity_data.head(100)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,Insufficient_Weight
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,Obesity_Type_II
3,Male,24,1.85,99.7,yes,no,2.4,3,Always,no,1.5,no,0.8,0.9,Frequently,Bike,Obesity_Type_III
4,Female,19,1.79,133.2,yes,yes,2.1,2,Sometimes,no,1.5,no,2.5,0.2,Sometimes,Automobile,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Male,17,1.98,106.3,yes,no,2.9,2,no,no,2.4,yes,0.4,0.4,Always,Walking,Insufficient_Weight
96,Male,15,1.80,129.3,no,yes,3.0,1,Always,no,1.0,yes,1.8,1.5,Always,Motorbike,Obesity_Type_I
97,Female,50,1.48,107.1,yes,no,2.6,2,Sometimes,yes,1.3,no,0.4,1.3,no,Motorbike,Obesity_Type_II
98,Female,51,1.91,54.3,no,yes,2.1,2,Sometimes,no,2.6,no,1.8,0.5,no,Public_Transportation,Overweight_Level_II
99,Female,55,1.72,96.0,no,yes,2.7,4,no,no,1.3,yes,2.2,1.2,Sometimes,Automobile,Obesity_Type_I

In [3]:
obesity_data.sample()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
1983,Male,46,1.5,94.8,no,no,2.3,2,no,no,2.3,no,2.6,0.0,Frequently,Automobile,Obesity_Type_I

In [4]:
obesity_data.sample(10,random_state=19)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
321,Male,43,1.77,134.7,yes,yes,1.2,3,no,yes,2.1,no,2.7,0.0,Sometimes,Bike,Obesity_Type_I
1775,Male,24,1.60,81.2,no,yes,1.8,4,Sometimes,no,1.8,no,1.4,0.4,Frequently,Motorbike,Obesity_Type_III
953,Male,35,1.89,82.3,yes,no,2.7,4,Always,yes,1.3,yes,2.9,0.4,Frequently,Bike,Obesity_Type_III
529,Female,39,1.74,105.7,no,yes,2.7,4,Sometimes,no,1.4,no,2.8,1.2,Frequently,Automobile,Obesity_Type_III
1878,Female,52,1.92,111.3,no,yes,2.1,1,no,no,2.1,yes,2.2,1.2,no,Automobile,Insufficient_Weight
123,Male,58,1.55,103.7,no,no,3.0,3,no,yes,1.0,no,0.4,1.2,Always,Walking,Overweight_Level_I
1953,Male,16,1.61,90.4,no,yes,2.5,2,Frequently,no,2.5,no,1.5,1.6,no,Walking,Obesity_Type_II
856,Female,50,1.51,53.9,yes,yes,2.8,1,Frequently,yes,1.5,no,1.0,0.6,Always,Bike,Overweight_Level_II
613,Male,48,1.76,68.4,yes,yes,1.1,4,no,no,2.5,yes,1.9,1.3,Always,Bike,Obesity_Type_I
1938,Male,39,1.90,114.6,yes,no,2.1,1,Frequently,yes,2.4,no,1.5,0.9,Always,Automobile,Overweight_Level_I

In [5]:
obesity_data.sample(2,random_state=9)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
207,Female,34,1.49,68.8,yes,no,1.3,1,Frequently,yes,1.5,yes,0.8,1.5,Frequently,Walking,Overweight_Level_I
756,Male,58,1.86,59.5,no,no,1.6,2,Sometimes,yes,1.9,no,2.3,2.0,Frequently,Walking,Insufficient_Weight

In [6]:
obesity_data.columns.tolist()

['Gender',
 'Age',
 'Height',
 'Weight',
 'family_history',
 'FAVC',
 'FCVC',
 'NCP',
 'CAEC',
 'SMOKE',
 'CH2O',
 'SCC',
 'FAF',
 'TUE',
 'CALC',
 'MTRANS',
 'Obesity']

In [7]:
obesity_data.shape

(2000, 17)

In [8]:
obesity_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          2000 non-null   object
 1   Age             2000 non-null   int64
 2   Height          2000 non-null   float64
 3   Weight          2000 non-null   float64
 4   family_history  2000 non-null   object
 5   FAVC            2000 non-null   object
 6   FCVC            2000 non-null   float64
 7   NCP             2000 non-null   int64
 8   CAEC            2000 non-null   object
 9   SMOKE           2000 non-null   object
 10  CH2O            2000 non-null   float64
 11  SCC             2000 non-null   object
 12  FAF             2000 non-null   float64
 13  TUE             2000 non-null   float64
 14  CALC            2000 non-null   object
 15  MTRANS          2000 non-null   object
 16  Obesity         2000 non-null   object
dtypes: float64(6), int64(2), object(9)
memory usage: 265.8+ KB

In [9]:
obesity_data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,39.641000,1.719110,92.266600,1.988250,2.498500,1.997650,1.501050,1.006200
std,15.042848,0.157683,27.634548,0.582346,1.115625,0.572987,0.879392,0.582092
min,14.000000,1.450000,45.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,26.000000,1.580000,68.200000,1.500000,2.000000,1.500000,0.700000,0.500000
50%,39.000000,1.710000,91.800000,2.000000,2.000000,2.000000,1.500000,1.000000
75%,53.000000,1.860000,115.800000,2.500000,3.000000,2.500000,2.300000,1.500000
max,65.000000,2.000000,140.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [10]:
obesity_data.loc[0:10, 'Age':'Height']

    Age  Height
0    27    1.46
1    15    1.52
2    49    1.47
3    24    1.85
4    19    1.79
5    46    1.90
6    34    1.64
7    30    1.95
8    51    1.47
9    22    1.54
10   49    1.70

In [11]:
obesity_data.loc[:,]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,Insufficient_Weight
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,Obesity_Type_II
3,Male,24,1.85,99.7,yes,no,2.4,3,Always,no,1.5,no,0.8,0.9,Frequently,Bike,Obesity_Type_III
4,Female,19,1.79,133.2,yes,yes,2.1,2,Sometimes,no,1.5,no,2.5,0.2,Sometimes,Automobile,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Female,26,1.97,122.6,yes,yes,1.8,3,Frequently,yes,1.3,no,0.6,1.6,no,Walking,Overweight_Level_II
1996,Male,42,1.79,108.8,yes,no,2.4,4,Sometimes,yes,2.1,yes,2.7,1.2,no,Bike,Overweight_Level_I
1997,Male,20,1.60,56.8,yes,yes,2.1,3,no,no,2.4,yes,1.2,0.1,Frequently,Walking,Obesity_Type_I
1998,Female,41,1.61,49.8,no,no,1.2,3,Always,yes,1.4,yes,1.9,0.0,Sometimes,Public_Transportation,Overweight_Level_I
1999,Female,33,1.87,75.8,yes,yes,3.0,1,no,yes,2.9,no,0.6,0.1,Sometimes,Walking,Overweight_Level_I

In [12]:
obesity_data.loc[200:,'Gender':'Weight']

      Gender  Age  Height  Weight
200   Female   27    1.50    87.8
201     Male   52    1.86   110.5
202   Female   54    1.63   114.3
203   Female   32    1.80    95.5
204   Female   45    1.66   126.1
...      ...  ...     ...     ...
1995  Female   26    1.97   122.6
1996    Male   42    1.79   108.8
1997    Male   20    1.60    56.8
1998  Female   41    1.61    49.8
1999  Female   33    1.87    75.8

[1800 rows x 4 columns]

In [13]:
obesity_data.iloc[2:5,2:5]

   Height  Weight family_history
2    1.47    45.7             no
3    1.85    99.7            yes
4    1.79   133.2            yes

Iloc using

In [14]:
obesity_data.iloc[:, 3:7]

      Weight family_history FAVC  FCVC
0      133.5             no   no   1.4
1      120.8             no  yes   2.4
2       45.7             no   no   1.6
3       99.7            yes   no   2.4
4      133.2            yes  yes   2.1
...      ...            ...  ...   ...
1995   122.6            yes  yes   1.8
1996   108.8            yes   no   2.4
1997    56.8            yes  yes   2.1
1998    49.8             no   no   1.2
1999    75.8            yes  yes   3.0

[2000 rows x 4 columns]

In [15]:
obesity_data.iloc[[10,20,30],[1,3,6]]

    Age  Weight  FCVC
10   49    47.8   1.7
20   60    99.1   1.9
30   52    96.2   2.0

In [16]:
obesity_data.at[0,'Age']

np.int64(27)

In [17]:
obesity_data.iat[0,3]

np.float64(133.5)

In [18]:
obesity_data[['Age','Weight','FCVC']]

      Age  Weight  FCVC
0      27   133.5   1.4
1      15   120.8   2.4
2      49    45.7   1.6
3      24    99.7   2.4
4      19   133.2   2.1
...   ...     ...   ...
1995   26   122.6   1.8
1996   42   108.8   2.4
1997   20    56.8   2.1
1998   41    49.8   1.2
1999   33    75.8   3.0

[2000 rows x 3 columns]

In [19]:
obesity_data.Age

0       27
1       15
2       49
3       24
4       19
        ..
1995    26
1996    42
1997    20
1998    41
1999    33
Name: Age, Length: 2000, dtype: int64

In [20]:
obesity_data.head(20)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,Insufficient_Weight
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,Obesity_Type_II
3,Male,24,1.85,99.7,yes,no,2.4,3,Always,no,1.5,no,0.8,0.9,Frequently,Bike,Obesity_Type_III
4,Female,19,1.79,133.2,yes,yes,2.1,2,Sometimes,no,1.5,no,2.5,0.2,Sometimes,Automobile,Obesity_Type_I
5,Male,46,1.90,67.6,no,yes,1.3,3,Sometimes,yes,1.6,no,1.6,0.8,Frequently,Bike,Obesity_Type_I
6,Female,34,1.64,80.9,no,no,2.8,1,Sometimes,no,3.0,no,2.1,1.8,Sometimes,Walking,Overweight_Level_I
7,Male,30,1.95,100.4,yes,no,2.6,1,Always,yes,2.2,no,2.3,1.6,no,Public_Transportation,Obesity_Type_I
8,Female,51,1.47,124.9,no,yes,2.6,2,no,no,2.5,no,2.4,0.2,Always,Public_Transportation,Obesity_Type_II
9,Female,22,1.54,139.2,yes,no,2.6,1,Always,yes,1.6,no,1.6,0.3,Sometimes,Bike,Obesity_Type_III
10,Male,49,1.70,47.8,yes,no,1.7,3,Always,yes,2.7,no,2.4,1.9,Frequently,Motorbike,Obesity_Type_II
11,Female,33,1.89,79.8,yes,no,2.5,2,Sometimes,yes,1.4,no,2.3,0.9,Sometimes,Automobile,Obesity_Type_III
12,Female,51,1.99,123.6,no,no,1.7,4,Sometimes,yes,1.4,yes,1.8,1.6,Always,Automobile,Insufficient_Weight
13,Female,64,1.84,123.1,no,no,1.9,4,Sometimes,no,1.3,yes,0.6,0.7,Always,Walking,Normal_Weight
14,Male,53,1.81,85.6,no,no,1.1,4,Always,yes,1.5,yes,3.0,0.8,Sometimes,Motorbike,Overweight_Level_I
15,Female,54,1.71,131.9,yes,no,2.8,4,Frequently,yes,1.5,no,2.9,1.3,no,Automobile,Insufficient_Weight
16,Female,54,1.57,94.8,yes,yes,1.7,1,Sometimes,no,2.6,yes,0.3,1.9,Frequently,Walking,Obesity_Type_III
17,Male,33,1.58,112.2,no,no,1.5,4,Sometimes,no,1.4,no,1.9,0.8,Frequently,Bike,Obesity_Type_II
18,Male,54,1.53,124.9,no,no,2.9,4,Frequently,no,2.1,no,0.2,0.0,Sometimes,Walking,Normal_Weight
19,Male,49,1.58,137.2,yes,no,1.3,2,Sometimes,yes,1.9,yes,0.8,1.9,Sometimes,Bike,Obesity_Type_III

In [21]:
obesity_data.loc[obesity_data.Age > 30]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,Obesity_Type_II
5,Male,46,1.90,67.6,no,yes,1.3,3,Sometimes,yes,1.6,no,1.6,0.8,Frequently,Bike,Obesity_Type_I
6,Female,34,1.64,80.9,no,no,2.8,1,Sometimes,no,3.0,no,2.1,1.8,Sometimes,Walking,Overweight_Level_I
8,Female,51,1.47,124.9,no,yes,2.6,2,no,no,2.5,no,2.4,0.2,Always,Public_Transportation,Obesity_Type_II
10,Male,49,1.70,47.8,yes,no,1.7,3,Always,yes,2.7,no,2.4,1.9,Frequently,Motorbike,Obesity_Type_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,Male,46,1.59,49.1,no,yes,2.7,1,Frequently,yes,2.0,no,2.1,0.1,Sometimes,Motorbike,Obesity_Type_III
1990,Female,39,1.94,48.0,no,no,2.3,4,no,no,1.1,yes,1.2,1.9,no,Motorbike,Obesity_Type_III
1996,Male,42,1.79,108.8,yes,no,2.4,4,Sometimes,yes,2.1,yes,2.7,1.2,no,Bike,Overweight_Level_I
1998,Female,41,1.61,49.8,no,no,1.2,3,Always,yes,1.4,yes,1.9,0.0,Sometimes,Public_Transportation,Overweight_Level_I
1999,Female,33,1.87,75.8,yes,yes,3.0,1,no,yes,2.9,no,0.6,0.1,Sometimes,Walking,Overweight_Level_I

In [22]:
obesity_data.loc[obesity_data.Weight > 1.5]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,Insufficient_Weight
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,Obesity_Type_II
3,Male,24,1.85,99.7,yes,no,2.4,3,Always,no,1.5,no,0.8,0.9,Frequently,Bike,Obesity_Type_III
4,Female,19,1.79,133.2,yes,yes,2.1,2,Sometimes,no,1.5,no,2.5,0.2,Sometimes,Automobile,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Female,26,1.97,122.6,yes,yes,1.8,3,Frequently,yes,1.3,no,0.6,1.6,no,Walking,Overweight_Level_II
1996,Male,42,1.79,108.8,yes,no,2.4,4,Sometimes,yes,2.1,yes,2.7,1.2,no,Bike,Overweight_Level_I
1997,Male,20,1.60,56.8,yes,yes,2.1,3,no,no,2.4,yes,1.2,0.1,Frequently,Walking,Obesity_Type_I
1998,Female,41,1.61,49.8,no,no,1.2,3,Always,yes,1.4,yes,1.9,0.0,Sometimes,Public_Transportation,Overweight_Level_I
1999,Female,33,1.87,75.8,yes,yes,3.0,1,no,yes,2.9,no,0.6,0.1,Sometimes,Walking,Overweight_Level_I

In [23]:
obesity_data

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,Insufficient_Weight
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,Obesity_Type_II
3,Male,24,1.85,99.7,yes,no,2.4,3,Always,no,1.5,no,0.8,0.9,Frequently,Bike,Obesity_Type_III
4,Female,19,1.79,133.2,yes,yes,2.1,2,Sometimes,no,1.5,no,2.5,0.2,Sometimes,Automobile,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Female,26,1.97,122.6,yes,yes,1.8,3,Frequently,yes,1.3,no,0.6,1.6,no,Walking,Overweight_Level_II
1996,Male,42,1.79,108.8,yes,no,2.4,4,Sometimes,yes,2.1,yes,2.7,1.2,no,Bike,Overweight_Level_I
1997,Male,20,1.60,56.8,yes,yes,2.1,3,no,no,2.4,yes,1.2,0.1,Frequently,Walking,Obesity_Type_I
1998,Female,41,1.61,49.8,no,no,1.2,3,Always,yes,1.4,yes,1.9,0.0,Sometimes,Public_Transportation,Overweight_Level_I
1999,Female,33,1.87,75.8,yes,yes,3.0,1,no,yes,2.9,no,0.6,0.1,Sometimes,Walking,Overweight_Level_I

In [24]:
obesity_data.loc[(obesity_data['Weight']>50) & (obesity_data['Obesity']=='Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
13,Female,64,1.84,123.1,no,no,1.9,4,Sometimes,no,1.3,yes,0.6,0.7,Always,Walking,Normal_Weight
18,Male,54,1.53,124.9,no,no,2.9,4,Frequently,no,2.1,no,0.2,0.0,Sometimes,Walking,Normal_Weight
20,Female,60,1.54,99.1,yes,yes,1.9,1,Sometimes,no,2.3,no,1.0,1.4,Frequently,Bike,Normal_Weight
21,Male,58,1.55,51.2,no,yes,1.4,3,Sometimes,no,1.6,yes,0.2,0.7,no,Automobile,Normal_Weight
35,Male,17,1.66,94.3,no,no,1.8,2,Sometimes,yes,2.6,yes,2.4,0.3,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1933,Female,55,1.89,134.0,yes,no,2.4,2,no,yes,1.3,no,1.9,1.7,Always,Bike,Normal_Weight
1967,Female,36,1.50,122.2,yes,no,1.9,4,Sometimes,yes,2.1,no,3.0,0.8,no,Motorbike,Normal_Weight
1975,Female,52,1.57,109.3,no,yes,2.9,2,Sometimes,yes,1.6,yes,2.1,0.2,Sometimes,Public_Transportation,Normal_Weight
1982,Female,35,1.64,52.6,no,yes,1.9,1,Sometimes,no,1.6,yes,1.0,1.6,Sometimes,Public_Transportation,Normal_Weight
1984,Male,35,1.78,72.2,yes,yes,1.8,1,Always,yes,2.2,yes,1.9,1.0,Always,Automobile,Normal_Weight

In [25]:
obesity_data.head(20)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,Insufficient_Weight
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,Obesity_Type_II
3,Male,24,1.85,99.7,yes,no,2.4,3,Always,no,1.5,no,0.8,0.9,Frequently,Bike,Obesity_Type_III
4,Female,19,1.79,133.2,yes,yes,2.1,2,Sometimes,no,1.5,no,2.5,0.2,Sometimes,Automobile,Obesity_Type_I
5,Male,46,1.90,67.6,no,yes,1.3,3,Sometimes,yes,1.6,no,1.6,0.8,Frequently,Bike,Obesity_Type_I
6,Female,34,1.64,80.9,no,no,2.8,1,Sometimes,no,3.0,no,2.1,1.8,Sometimes,Walking,Overweight_Level_I
7,Male,30,1.95,100.4,yes,no,2.6,1,Always,yes,2.2,no,2.3,1.6,no,Public_Transportation,Obesity_Type_I
8,Female,51,1.47,124.9,no,yes,2.6,2,no,no,2.5,no,2.4,0.2,Always,Public_Transportation,Obesity_Type_II
9,Female,22,1.54,139.2,yes,no,2.6,1,Always,yes,1.6,no,1.6,0.3,Sometimes,Bike,Obesity_Type_III
10,Male,49,1.70,47.8,yes,no,1.7,3,Always,yes,2.7,no,2.4,1.9,Frequently,Motorbike,Obesity_Type_II
11,Female,33,1.89,79.8,yes,no,2.5,2,Sometimes,yes,1.4,no,2.3,0.9,Sometimes,Automobile,Obesity_Type_III
12,Female,51,1.99,123.6,no,no,1.7,4,Sometimes,yes,1.4,yes,1.8,1.6,Always,Automobile,Insufficient_Weight
13,Female,64,1.84,123.1,no,no,1.9,4,Sometimes,no,1.3,yes,0.6,0.7,Always,Walking,Normal_Weight
14,Male,53,1.81,85.6,no,no,1.1,4,Always,yes,1.5,yes,3.0,0.8,Sometimes,Motorbike,Overweight_Level_I
15,Female,54,1.71,131.9,yes,no,2.8,4,Frequently,yes,1.5,no,2.9,1.3,no,Automobile,Insufficient_Weight
16,Female,54,1.57,94.8,yes,yes,1.7,1,Sometimes,no,2.6,yes,0.3,1.9,Frequently,Walking,Obesity_Type_III
17,Male,33,1.58,112.2,no,no,1.5,4,Sometimes,no,1.4,no,1.9,0.8,Frequently,Bike,Obesity_Type_II
18,Male,54,1.53,124.9,no,no,2.9,4,Frequently,no,2.1,no,0.2,0.0,Sometimes,Walking,Normal_Weight
19,Male,49,1.58,137.2,yes,no,1.3,2,Sometimes,yes,1.9,yes,0.8,1.9,Sometimes,Bike,Obesity_Type_III

In [26]:
obesity_data[obesity_data['Height']>1]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,Insufficient_Weight
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,Obesity_Type_II
3,Male,24,1.85,99.7,yes,no,2.4,3,Always,no,1.5,no,0.8,0.9,Frequently,Bike,Obesity_Type_III
4,Female,19,1.79,133.2,yes,yes,2.1,2,Sometimes,no,1.5,no,2.5,0.2,Sometimes,Automobile,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Female,26,1.97,122.6,yes,yes,1.8,3,Frequently,yes,1.3,no,0.6,1.6,no,Walking,Overweight_Level_II
1996,Male,42,1.79,108.8,yes,no,2.4,4,Sometimes,yes,2.1,yes,2.7,1.2,no,Bike,Overweight_Level_I
1997,Male,20,1.60,56.8,yes,yes,2.1,3,no,no,2.4,yes,1.2,0.1,Frequently,Walking,Obesity_Type_I
1998,Female,41,1.61,49.8,no,no,1.2,3,Always,yes,1.4,yes,1.9,0.0,Sometimes,Public_Transportation,Overweight_Level_I
1999,Female,33,1.87,75.8,yes,yes,3.0,1,no,yes,2.9,no,0.6,0.1,Sometimes,Walking,Overweight_Level_I

In [27]:
obesity_data.loc[(obesity_data['Height'])<2]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,Insufficient_Weight
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,Obesity_Type_II
3,Male,24,1.85,99.7,yes,no,2.4,3,Always,no,1.5,no,0.8,0.9,Frequently,Bike,Obesity_Type_III
4,Female,19,1.79,133.2,yes,yes,2.1,2,Sometimes,no,1.5,no,2.5,0.2,Sometimes,Automobile,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Female,26,1.97,122.6,yes,yes,1.8,3,Frequently,yes,1.3,no,0.6,1.6,no,Walking,Overweight_Level_II
1996,Male,42,1.79,108.8,yes,no,2.4,4,Sometimes,yes,2.1,yes,2.7,1.2,no,Bike,Overweight_Level_I
1997,Male,20,1.60,56.8,yes,yes,2.1,3,no,no,2.4,yes,1.2,0.1,Frequently,Walking,Obesity_Type_I
1998,Female,41,1.61,49.8,no,no,1.2,3,Always,yes,1.4,yes,1.9,0.0,Sometimes,Public_Transportation,Overweight_Level_I
1999,Female,33,1.87,75.8,yes,yes,3.0,1,no,yes,2.9,no,0.6,0.1,Sometimes,Walking,Overweight_Level_I

In [28]:
obesity_data

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,Insufficient_Weight
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,Obesity_Type_II
3,Male,24,1.85,99.7,yes,no,2.4,3,Always,no,1.5,no,0.8,0.9,Frequently,Bike,Obesity_Type_III
4,Female,19,1.79,133.2,yes,yes,2.1,2,Sometimes,no,1.5,no,2.5,0.2,Sometimes,Automobile,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Female,26,1.97,122.6,yes,yes,1.8,3,Frequently,yes,1.3,no,0.6,1.6,no,Walking,Overweight_Level_II
1996,Male,42,1.79,108.8,yes,no,2.4,4,Sometimes,yes,2.1,yes,2.7,1.2,no,Bike,Overweight_Level_I
1997,Male,20,1.60,56.8,yes,yes,2.1,3,no,no,2.4,yes,1.2,0.1,Frequently,Walking,Obesity_Type_I
1998,Female,41,1.61,49.8,no,no,1.2,3,Always,yes,1.4,yes,1.9,0.0,Sometimes,Public_Transportation,Overweight_Level_I
1999,Female,33,1.87,75.8,yes,yes,3.0,1,no,yes,2.9,no,0.6,0.1,Sometimes,Walking,Overweight_Level_I

In [29]:
obesity_data.loc[:,'Age']

0       27
1       15
2       49
3       24
4       19
        ..
1995    26
1996    42
1997    20
1998    41
1999    33
Name: Age, Length: 2000, dtype: int64

In [30]:
obesity_data.loc[(obesity_data['Age']>28) & (obesity_data['Gender']=='Male')].head(10)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,Obesity_Type_II
5,Male,46,1.90,67.6,no,yes,1.3,3,Sometimes,yes,1.6,no,1.6,0.8,Frequently,Bike,Obesity_Type_I
7,Male,30,1.95,100.4,yes,no,2.6,1,Always,yes,2.2,no,2.3,1.6,no,Public_Transportation,Obesity_Type_I
10,Male,49,1.70,47.8,yes,no,1.7,3,Always,yes,2.7,no,2.4,1.9,Frequently,Motorbike,Obesity_Type_II
14,Male,53,1.81,85.6,no,no,1.1,4,Always,yes,1.5,yes,3.0,0.8,Sometimes,Motorbike,Overweight_Level_I
17,Male,33,1.58,112.2,no,no,1.5,4,Sometimes,no,1.4,no,1.9,0.8,Frequently,Bike,Obesity_Type_II
18,Male,54,1.53,124.9,no,no,2.9,4,Frequently,no,2.1,no,0.2,0.0,Sometimes,Walking,Normal_Weight
19,Male,49,1.58,137.2,yes,no,1.3,2,Sometimes,yes,1.9,yes,0.8,1.9,Sometimes,Bike,Obesity_Type_III
21,Male,58,1.55,51.2,no,yes,1.4,3,Sometimes,no,1.6,yes,0.2,0.7,no,Automobile,Normal_Weight
22,Male,47,1.95,114.8,yes,no,1.7,2,Sometimes,no,2.1,no,1.5,0.0,Sometimes,Motorbike,Obesity_Type_III

In [31]:
obesity_data.loc[(obesity_data['Gender']=='Female')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
4,Female,19,1.79,133.2,yes,yes,2.1,2,Sometimes,no,1.5,no,2.5,0.2,Sometimes,Automobile,Obesity_Type_I
6,Female,34,1.64,80.9,no,no,2.8,1,Sometimes,no,3.0,no,2.1,1.8,Sometimes,Walking,Overweight_Level_I
8,Female,51,1.47,124.9,no,yes,2.6,2,no,no,2.5,no,2.4,0.2,Always,Public_Transportation,Obesity_Type_II
9,Female,22,1.54,139.2,yes,no,2.6,1,Always,yes,1.6,no,1.6,0.3,Sometimes,Bike,Obesity_Type_III
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,Female,17,1.56,105.2,yes,no,2.7,2,Frequently,yes,1.1,no,0.6,1.8,Frequently,Walking,Insufficient_Weight
1994,Female,25,1.65,115.3,no,no,1.1,2,Sometimes,yes,2.5,yes,0.0,0.3,Sometimes,Automobile,Obesity_Type_II
1995,Female,26,1.97,122.6,yes,yes,1.8,3,Frequently,yes,1.3,no,0.6,1.6,no,Walking,Overweight_Level_II
1998,Female,41,1.61,49.8,no,no,1.2,3,Always,yes,1.4,yes,1.9,0.0,Sometimes,Public_Transportation,Overweight_Level_I
1999,Female,33,1.87,75.8,yes,yes,3.0,1,no,yes,2.9,no,0.6,0.1,Sometimes,Walking,Overweight_Level_I

In [32]:
obesity_data.loc[(obesity_data['Gender']=='Female') & (obesity_data['Age']>25)]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
6,Female,34,1.64,80.9,no,no,2.8,1,Sometimes,no,3.0,no,2.1,1.8,Sometimes,Walking,Overweight_Level_I
8,Female,51,1.47,124.9,no,yes,2.6,2,no,no,2.5,no,2.4,0.2,Always,Public_Transportation,Obesity_Type_II
11,Female,33,1.89,79.8,yes,no,2.5,2,Sometimes,yes,1.4,no,2.3,0.9,Sometimes,Automobile,Obesity_Type_III
12,Female,51,1.99,123.6,no,no,1.7,4,Sometimes,yes,1.4,yes,1.8,1.6,Always,Automobile,Insufficient_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,Female,26,1.95,107.4,no,yes,2.2,2,Frequently,yes,2.5,no,2.0,1.0,Always,Walking,Overweight_Level_II
1990,Female,39,1.94,48.0,no,no,2.3,4,no,no,1.1,yes,1.2,1.9,no,Motorbike,Obesity_Type_III
1995,Female,26,1.97,122.6,yes,yes,1.8,3,Frequently,yes,1.3,no,0.6,1.6,no,Walking,Overweight_Level_II
1998,Female,41,1.61,49.8,no,no,1.2,3,Always,yes,1.4,yes,1.9,0.0,Sometimes,Public_Transportation,Overweight_Level_I
1999,Female,33,1.87,75.8,yes,yes,3.0,1,no,yes,2.9,no,0.6,0.1,Sometimes,Walking,Overweight_Level_I

In [33]:
obesity_data[obesity_data['Obesity'].str.startswith('Normal')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
13,Female,64,1.84,123.1,no,no,1.9,4,Sometimes,no,1.3,yes,0.6,0.7,Always,Walking,Normal_Weight
18,Male,54,1.53,124.9,no,no,2.9,4,Frequently,no,2.1,no,0.2,0.0,Sometimes,Walking,Normal_Weight
20,Female,60,1.54,99.1,yes,yes,1.9,1,Sometimes,no,2.3,no,1.0,1.4,Frequently,Bike,Normal_Weight
21,Male,58,1.55,51.2,no,yes,1.4,3,Sometimes,no,1.6,yes,0.2,0.7,no,Automobile,Normal_Weight
35,Male,17,1.66,94.3,no,no,1.8,2,Sometimes,yes,2.6,yes,2.4,0.3,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1967,Female,36,1.50,122.2,yes,no,1.9,4,Sometimes,yes,2.1,no,3.0,0.8,no,Motorbike,Normal_Weight
1975,Female,52,1.57,109.3,no,yes,2.9,2,Sometimes,yes,1.6,yes,2.1,0.2,Sometimes,Public_Transportation,Normal_Weight
1981,Female,55,1.59,48.3,yes,no,2.1,3,Sometimes,yes,1.6,yes,2.3,0.4,no,Motorbike,Normal_Weight
1982,Female,35,1.64,52.6,no,yes,1.9,1,Sometimes,no,1.6,yes,1.0,1.6,Sometimes,Public_Transportation,Normal_Weight
1984,Male,35,1.78,72.2,yes,yes,1.8,1,Always,yes,2.2,yes,1.9,1.0,Always,Automobile,Normal_Weight

In [34]:
obesity_data[obesity_data['SMOKE'].str.contains('yes')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,Insufficient_Weight
5,Male,46,1.90,67.6,no,yes,1.3,3,Sometimes,yes,1.6,no,1.6,0.8,Frequently,Bike,Obesity_Type_I
7,Male,30,1.95,100.4,yes,no,2.6,1,Always,yes,2.2,no,2.3,1.6,no,Public_Transportation,Obesity_Type_I
9,Female,22,1.54,139.2,yes,no,2.6,1,Always,yes,1.6,no,1.6,0.3,Sometimes,Bike,Obesity_Type_III
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,Female,25,1.65,115.3,no,no,1.1,2,Sometimes,yes,2.5,yes,0.0,0.3,Sometimes,Automobile,Obesity_Type_II
1995,Female,26,1.97,122.6,yes,yes,1.8,3,Frequently,yes,1.3,no,0.6,1.6,no,Walking,Overweight_Level_II
1996,Male,42,1.79,108.8,yes,no,2.4,4,Sometimes,yes,2.1,yes,2.7,1.2,no,Bike,Overweight_Level_I
1998,Female,41,1.61,49.8,no,no,1.2,3,Always,yes,1.4,yes,1.9,0.0,Sometimes,Public_Transportation,Overweight_Level_I
1999,Female,33,1.87,75.8,yes,yes,3.0,1,no,yes,2.9,no,0.6,0.1,Sometimes,Walking,Overweight_Level_I

In [35]:
print(obesity_data.columns.tolist())

['Gender', 'Age', 'Height', 'Weight', 'family_history', 'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS', 'Obesity']

In [36]:
obesity_data.columns = obesity_data.columns.str.strip()
obesity_data.head(2)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,Overweight_Level_II
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,Insufficient_Weight

In [37]:
obesity_data.columns = obesity_data.columns.str.strip()
obesity_data = obesity_data.iloc[:, :-1]
obesity_data.head(2)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike

In [38]:
obesity_data['Dummy']='dummy'

In [39]:
obesity_data.head(4)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Dummy
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,dummy
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,dummy
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,dummy
3,Male,24,1.85,99.7,yes,no,2.4,3,Always,no,1.5,no,0.8,0.9,Frequently,Bike,dummy

In [40]:
obesity_data=obesity_data.iloc[:,:-1]
obesity_data.head(3)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,Female,27,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile

In [41]:
obesity_data.loc[0,'Age']=23
obesity_data.head(1)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,Female,23,1.46,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike

In [42]:
obesity_data.iloc[0,2]=24
obesity_data.head(1)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,Female,23,24.0,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike

In [43]:
obesity_data['Dummy']='dummy'
obesity_data.head(3)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Dummy
0,Female,23,24.00,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,dummy
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,dummy
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,dummy

In [44]:
obesity_data=obesity_data.drop('Dummy',axis=1)
obesity_data.head(3)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,Female,23,24.00,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile

In [45]:
import numpy as np

In [46]:
obesity_data['New_age_catgory']=np.where(obesity_data['Age']<25,'very young','not so young')
obesity_data.head(30)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,New_age_catgory
0,Female,23,24.00,133.5,no,no,1.4,1,Sometimes,yes,1.0,no,1.6,0.9,no,Motorbike,very young
1,Male,15,1.52,120.8,no,yes,2.4,2,no,yes,2.3,yes,0.4,2.0,Sometimes,Bike,very young
2,Male,49,1.47,45.7,no,no,1.6,3,no,no,1.1,no,2.2,1.7,Frequently,Automobile,not so young
3,Male,24,1.85,99.7,yes,no,2.4,3,Always,no,1.5,no,0.8,0.9,Frequently,Bike,very young
4,Female,19,1.79,133.2,yes,yes,2.1,2,Sometimes,no,1.5,no,2.5,0.2,Sometimes,Automobile,very young
5,Male,46,1.90,67.6,no,yes,1.3,3,Sometimes,yes,1.6,no,1.6,0.8,Frequently,Bike,not so young
6,Female,34,1.64,80.9,no,no,2.8,1,Sometimes,no,3.0,no,2.1,1.8,Sometimes,Walking,not so young
7,Male,30,1.95,100.4,yes,no,2.6,1,Always,yes,2.2,no,2.3,1.6,no,Public_Transportation,not so young
8,Female,51,1.47,124.9,no,yes,2.6,2,no,no,2.5,no,2.4,0.2,Always,Public_Transportation,not so young
9,Female,22,1.54,139.2,yes,no,2.6,1,Always,yes,1.6,no,1.6,0.3,Sometimes,Bike,very young
10,Male,49,1.70,47.8,yes,no,1.7,3,Always,yes,2.7,no,2.4,1.9,Frequently,Motorbike,not so young
11,Female,33,1.89,79.8,yes,no,2.5,2,Sometimes,yes,1.4,no,2.3,0.9,Sometimes,Automobile,not so young
12,Female,51,1.99,123.6,no,no,1.7,4,Sometimes,yes,1.4,yes,1.8,1.6,Always,Automobile,not so young
13,Female,64,1.84,123.1,no,no,1.9,4,Sometimes,no,1.3,yes,0.6,0.7,Always,Walking,not so young
14,Male,53,1.81,85.6,no,no,1.1,4,Always,yes,1.5,yes,3.0,0.8,Sometimes,Motorbike,not so young
15,Female,54,1.71,131.9,yes,no,2.8,4,Frequently,yes,1.5,no,2.9,1.3,no,Automobile,not so young
16,Female,54,1.57,94.8,yes,yes,1.7,1,Sometimes,no,2.6,yes,0.3,1.9,Frequently,Walking,not so young
17,Male,33,1.58,112.2,no,no,1.5,4,Sometimes,no,1.4,no,1.9,0.8,Frequently,Bike,not so young
18,Male,54,1.53,124.9,no,no,2.9,4,Frequently,no,2.1,no,0.2,0.0,Sometimes,Walking,not so young
19,Male,49,1.58,137.2,yes,no,1.3,2,Sometimes,yes,1.9,yes,0.8,1.9,Sometimes,Bike,not so young
20,Female,60,1.54,99.1,yes,yes,1.9,1,Sometimes,no,2.3,no,1.0,1.4,Frequently,Bike,not so young
21,Male,58,1.55,51.2,no,yes,1.4,3,Sometimes,no,1.6,yes,0.2,0.7,no,Automobile,not so young
22,Male,47,1.95,114.8,yes,no,1.7,2,Sometimes,no,2.1,no,1.5,0.0,Sometimes,Motorbike,not so young
23,Female,59,1.86,95.0,no,no,2.3,4,Sometimes,no,2.7,no,1.1,0.4,Frequently,Automobile,not so young
24,Female,47,1.60,139.0,yes,no,2.8,1,Always,no,2.4,no,1.8,0.9,Frequently,Motorbike,not so young
25,Male,47,1.49,93.9,no,no,1.7,4,Always,yes,2.4,yes,1.5,1.0,Sometimes,Bike,not so young
26,Male,32,1.82,62.2,no,yes,2.1,3,Sometimes,no,2.0,yes,1.6,0.5,Sometimes,Automobile,not so young
27,Female,60,1.52,129.7,no,no,2.3,3,Frequently,yes,1.1,yes,1.7,1.8,Sometimes,Automobile,not so young
28,Male,54,1.73,48.2,yes,yes,1.9,3,Frequently,no,1.2,no,0.6,1.2,no,Public_Transportation,not so young
29,Male,58,1.65,86.5,yes,yes,2.0,4,Sometimes,yes,2.2,yes,0.3,1.2,Always,Walking,not so young