In [3]:
import pandas as pd

In [4]:
vegas=['beetroot','carrot','tomato','kovakkai','coconut']

In [5]:
vegas_Series =pd.Series(vegas, index=['purple','orange','red','green','white'])
vegas_Series

purple    beetroot
orange      carrot
red         tomato
green     kovakkai
white      coconut
dtype: object

In [6]:
vege_dict= {'red':'tomato','green':'kovakkai'}

In [7]:
vege_dict_series=pd.Series(vege_dict)
vege_dict_series

red        tomato
green    kovakkai
dtype: object

In [8]:
vege_dict_series['orange']='carrot'

In [9]:
vege_dict_series

red         tomato
green     kovakkai
orange      carrot
dtype: object

In [10]:
vege_dict_series['white']='coconut'

In [11]:
vege_dict_series

red         tomato
green     kovakkai
orange      carrot
white      coconut
dtype: object

In [12]:
vege_dict_series.drop(['orange'],inplace=True)

In [13]:
vege_dict_series

red        tomato
green    kovakkai
white     coconut
dtype: object

In [14]:
data = { 'vegetables': ['beetroot', 'carrot', 'redchilli', 'beans', 'coconut'],
       'color' : ['purple', 'orange', 'red', 'green', 'white'],
        'unit' : ['1kg', '1kg','1kg','1kg','1piece'],
       'min' : [25, 35, 33, 40, 'seventeen'],
       'max': [40, 45, 90, 45, 38],
       }

In [15]:
marketdf=pd.DataFrame(data,index=['a','b','c','d','e'])

In [16]:
marketdf

  vegetables   color    unit        min  max
a   beetroot  purple     1kg         25   40
b     carrot  orange     1kg         35   45
c  redchilli     red     1kg         33   90
d      beans   green     1kg         40   45
e    coconut   white  1piece  seventeen   38

In [17]:
marketdf.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [18]:
marketdf['unit']

a       1kg
b       1kg
c       1kg
d       1kg
e    1piece
Name: unit, dtype: object

In [19]:
marketdf.loc['a']

vegetables    beetroot
color           purple
unit               1kg
min                 25
max                 40
Name: a, dtype: object

its shown as the a value (index in the given market data)

In [20]:
marketdf.loc['a','vegetables']

'beetroot'

In [21]:
marketdf

  vegetables   color    unit        min  max
a   beetroot  purple     1kg         25   40
b     carrot  orange     1kg         35   45
c  redchilli     red     1kg         33   90
d      beans   green     1kg         40   45
e    coconut   white  1piece  seventeen   38

In [22]:
marketdf.loc['f']={'vegetables':'pumpkin','color':'yellow','unit':'1piece','min':28,'max':33}
marketdf

  vegetables   color    unit        min  max
a   beetroot  purple     1kg         25   40
b     carrot  orange     1kg         35   45
c  redchilli     red     1kg         33   90
d      beans   green     1kg         40   45
e    coconut   white  1piece  seventeen   38
f    pumpkin  yellow  1piece         28   33

In [23]:
marketdf

  vegetables   color    unit        min  max
a   beetroot  purple     1kg         25   40
b     carrot  orange     1kg         35   45
c  redchilli     red     1kg         33   90
d      beans   green     1kg         40   45
e    coconut   white  1piece  seventeen   38
f    pumpkin  yellow  1piece         28   33

In [24]:
marketdf.loc['a','unit']

'1kg'

In [26]:
marketdf.loc['g']={'vegetables':'lemon','color':'yellow','unit':10,'min':28,'max':33}

In [27]:
marketdf

  vegetables   color    unit        min  max
a   beetroot  purple     1kg         25   40
b     carrot  orange     1kg         35   45
c  redchilli     red     1kg         33   90
d      beans   green     1kg         40   45
e    coconut   white  1piece  seventeen   38
f    pumpkin  yellow  1piece         28   33
g      lemon  yellow      10         28   33

In [29]:
marketdf.isna()

   vegetables  color   unit    min    max
a       False  False  False  False  False
b       False  False  False  False  False
c       False  False  False  False  False
d       False  False  False  False  False
e       False  False  False  False  False
f       False  False  False  False  False
g       False  False  False  False  False