<a href="https://colab.research.google.com/github/Karthikeyan-Analyst/pandas-practice/blob/Python_practice/uberdata_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd

data = {
    'trip_id': list(range(1, 26)),
    'date': [
        '2024-01-01','2024-01-01','2024-01-01','2024-01-01','2024-01-02',
        '2024-01-02','2024-01-02','2024-01-02','2024-01-03','2024-01-03',
        '2024-01-03','2024-01-03','2024-01-04','2024-01-04','2024-01-04',
        '2024-01-04','2024-01-05','2024-01-05','2024-01-05','2024-01-05',
        '2024-01-06','2024-01-06','2024-01-06','2024-01-06','2024-01-07'
    ],
    'pickup_location': [
        'Chennai Airport','T Nagar','Velachery','OMR','Tambaram',
        'Adyar','Perungudi','Anna Nagar','Guindy','T Nagar',
        'Navalur','Kodambakkam','Chengalpattu','Velachery','Teynampet',
        'Thiruvanmiyur','ECR','Kilpauk','MMDA','Madhavaram',
        'Koyambedu','Porur','Ambattur','Pallavaram','T Nagar'
    ],
    'drop_location': [
        'T Nagar','OMR','Guindy','Navalur','Airport',
        'Velachery','Chennai Airport','T Nagar','OMR','Adyar',
        'Guindy','ECR','Tambaram','Ann Nagar','OMR',
        'Perungudi','T Nagar','Airport','Ambattur','Perambur',
        'Guindy','Thoraipakkam','Velachery','MMDA','OMR'
    ],
    'distance_km': [
        12.5, 8.2, 5.4, 14.0, 10.1,
        11.3, 18.2, 7.5, 13.4, 9.0,
        15.6, 6.3, 41.2, 4.8, 8.5,
        6.7, 22.0, 11.1, 16.5, 12.2,
        9.8, 14.7, 7.9, 10.4, 13.6
    ],
    'fare_amount': [
        350, 210, 150, 290, 300,
        250, 520, 180, 360, 220,
        450, 160, 900, 140, 200,
        180, 600, 260, 430, 310,
        230, 320, 190, 275, 330
    ],
    'payment_type': [
        'UPI','Cash','UPI','Card','UPI',
        'Cash','Card','UPI','Cash','UPI',
        'UPI','Card','UPI','Cash','Card',
        'UPI','UPI','Cash','UPI','Card',
        'Cash','UPI','Card','UPI','Cash'
    ],
    'driver_rating': [
        4.8, 4.5, 5.0, 4.6, 4.2,
        4.3, 4.7, 4.4, 4.1, 4.9,
        4.8, 4.5, 4.0, 5.0, 4.6,
        4.3, 4.8, 4.5, 4.7, 4.4,
        4.2, 4.1, 4.9, 4.6, 4.8
    ]
}

df = pd.DataFrame(data)
df.to_csv("uber_trips.csv", index=False)
df

,trip_id,date,pickup_location,drop_location,distance_km,fare_amount,payment_type,driver_rating
0,1,2024-01-01,Chennai Airport,T Nagar,12.5,350,UPI,4.8
1,2,2024-01-01,T Nagar,OMR,8.2,210,Cash,4.5
2,3,2024-01-01,Velachery,Guindy,5.4,150,UPI,5.0
3,4,2024-01-01,OMR,Navalur,14.0,290,Card,4.6
4,5,2024-01-02,Tambaram,Airport,10.1,300,UPI,4.2
5,6,2024-01-02,Adyar,Velachery,11.3,250,Cash,4.3
6,7,2024-01-02,Perungudi,Chennai Airport,18.2,520,Card,4.7
7,8,2024-01-02,Anna Nagar,T Nagar,7.5,180,UPI,4.4
8,9,2024-01-03,Guindy,OMR,13.4,360,Cash,4.1
9,10,2024-01-03,T Nagar,Adyar,9.0,220,UPI,4.9
10,11,2024-01-03,Navalur,Guindy,15.6,450,UPI,4.8
11,12,2024-01-03,Kodambakkam,ECR,6.3,160,Card,4.5
12,13,2024-01-04,Chengalpattu,Tambaram,41.2,900,UPI,4.0
13,14,2024-01-04,Velachery,Ann Nagar,4.8,140,Cash,5.0
14,15,2024-01-04,Teynampet,OMR,8.5,200,Card,4.6
15,16,2024-01-04,Thiruvanmiyur,Perungudi,6.7,180,UPI,4.3
16,17,2024-01-05,ECR,T Nagar,22.0,600,UPI,4.8
17,18,2024-01-05,Kilpauk,Airport,11.1,260,Cash,4.5
18,19,2024-01-05,MMDA,Ambattur,16.5,430,UPI,4.7
19,20,2024-01-05,Madhavaram,Perambur,12.2,310,Card,4.4
20,21,2024-01-06,Koyambedu,Guindy,9.8,230,Cash,4.2
21,22,2024-01-06,Porur,Thoraipakkam,14.7,320,UPI,4.1
22,23,2024-01-06,Ambattur,Velachery,7.9,190,Card,4.9
23,24,2024-01-06,Pallavaram,MMDA,10.4,275,UPI,4.6
24,25,2024-01-07,T Nagar,OMR,13.6,330,Cash,4.8

In [2]:
df.head()

,trip_id,date,pickup_location,drop_location,distance_km,fare_amount,payment_type,driver_rating
0,1,2024-01-01,Chennai Airport,T Nagar,12.5,350,UPI,4.8
1,2,2024-01-01,T Nagar,OMR,8.2,210,Cash,4.5
2,3,2024-01-01,Velachery,Guindy,5.4,150,UPI,5.0
3,4,2024-01-01,OMR,Navalur,14.0,290,Card,4.6
4,5,2024-01-02,Tambaram,Airport,10.1,300,UPI,4.2

In [3]:
df.info()
df.describe()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   trip_id          25 non-null     int64
 1   date             25 non-null     object
 2   pickup_location  25 non-null     object
 3   drop_location    25 non-null     object
 4   distance_km      25 non-null     float64
 5   fare_amount      25 non-null     int64
 6   payment_type     25 non-null     object
 7   driver_rating    25 non-null     float64
dtypes: float64(2), int64(2), object(4)
memory usage: 1.7+ KB

(25, 8)

In [4]:
df.isnull().sum()

trip_id            0
date               0
pickup_location    0
drop_location      0
distance_km        0
fare_amount        0
payment_type       0
driver_rating      0
dtype: int64

In [5]:
df['date']=pd.to_datetime(df['date'])
df

,trip_id,date,pickup_location,drop_location,distance_km,fare_amount,payment_type,driver_rating
0,1,2024-01-01,Chennai Airport,T Nagar,12.5,350,UPI,4.8
1,2,2024-01-01,T Nagar,OMR,8.2,210,Cash,4.5
2,3,2024-01-01,Velachery,Guindy,5.4,150,UPI,5.0
3,4,2024-01-01,OMR,Navalur,14.0,290,Card,4.6
4,5,2024-01-02,Tambaram,Airport,10.1,300,UPI,4.2
5,6,2024-01-02,Adyar,Velachery,11.3,250,Cash,4.3
6,7,2024-01-02,Perungudi,Chennai Airport,18.2,520,Card,4.7
7,8,2024-01-02,Anna Nagar,T Nagar,7.5,180,UPI,4.4
8,9,2024-01-03,Guindy,OMR,13.4,360,Cash,4.1
9,10,2024-01-03,T Nagar,Adyar,9.0,220,UPI,4.9
10,11,2024-01-03,Navalur,Guindy,15.6,450,UPI,4.8
11,12,2024-01-03,Kodambakkam,ECR,6.3,160,Card,4.5
12,13,2024-01-04,Chengalpattu,Tambaram,41.2,900,UPI,4.0
13,14,2024-01-04,Velachery,Ann Nagar,4.8,140,Cash,5.0
14,15,2024-01-04,Teynampet,OMR,8.5,200,Card,4.6
15,16,2024-01-04,Thiruvanmiyur,Perungudi,6.7,180,UPI,4.3
16,17,2024-01-05,ECR,T Nagar,22.0,600,UPI,4.8
17,18,2024-01-05,Kilpauk,Airport,11.1,260,Cash,4.5
18,19,2024-01-05,MMDA,Ambattur,16.5,430,UPI,4.7
19,20,2024-01-05,Madhavaram,Perambur,12.2,310,Card,4.4
20,21,2024-01-06,Koyambedu,Guindy,9.8,230,Cash,4.2
21,22,2024-01-06,Porur,Thoraipakkam,14.7,320,UPI,4.1
22,23,2024-01-06,Ambattur,Velachery,7.9,190,Card,4.9
23,24,2024-01-06,Pallavaram,MMDA,10.4,275,UPI,4.6
24,25,2024-01-07,T Nagar,OMR,13.6,330,Cash,4.8

In [6]:
df['hour'] = df['date'].dt.hour
df

,trip_id,date,pickup_location,drop_location,distance_km,fare_amount,payment_type,driver_rating,hour
0,1,2024-01-01,Chennai Airport,T Nagar,12.5,350,UPI,4.8,0
1,2,2024-01-01,T Nagar,OMR,8.2,210,Cash,4.5,0
2,3,2024-01-01,Velachery,Guindy,5.4,150,UPI,5.0,0
3,4,2024-01-01,OMR,Navalur,14.0,290,Card,4.6,0
4,5,2024-01-02,Tambaram,Airport,10.1,300,UPI,4.2,0
5,6,2024-01-02,Adyar,Velachery,11.3,250,Cash,4.3,0
6,7,2024-01-02,Perungudi,Chennai Airport,18.2,520,Card,4.7,0
7,8,2024-01-02,Anna Nagar,T Nagar,7.5,180,UPI,4.4,0
8,9,2024-01-03,Guindy,OMR,13.4,360,Cash,4.1,0
9,10,2024-01-03,T Nagar,Adyar,9.0,220,UPI,4.9,0
10,11,2024-01-03,Navalur,Guindy,15.6,450,UPI,4.8,0
11,12,2024-01-03,Kodambakkam,ECR,6.3,160,Card,4.5,0
12,13,2024-01-04,Chengalpattu,Tambaram,41.2,900,UPI,4.0,0
13,14,2024-01-04,Velachery,Ann Nagar,4.8,140,Cash,5.0,0
14,15,2024-01-04,Teynampet,OMR,8.5,200,Card,4.6,0
15,16,2024-01-04,Thiruvanmiyur,Perungudi,6.7,180,UPI,4.3,0
16,17,2024-01-05,ECR,T Nagar,22.0,600,UPI,4.8,0
17,18,2024-01-05,Kilpauk,Airport,11.1,260,Cash,4.5,0
18,19,2024-01-05,MMDA,Ambattur,16.5,430,UPI,4.7,0
19,20,2024-01-05,Madhavaram,Perambur,12.2,310,Card,4.4,0
20,21,2024-01-06,Koyambedu,Guindy,9.8,230,Cash,4.2,0
21,22,2024-01-06,Porur,Thoraipakkam,14.7,320,UPI,4.1,0
22,23,2024-01-06,Ambattur,Velachery,7.9,190,Card,4.9,0
23,24,2024-01-06,Pallavaram,MMDA,10.4,275,UPI,4.6,0
24,25,2024-01-07,T Nagar,OMR,13.6,330,Cash,4.8,0

In [7]:
df['day']=df['date'].dt.day_name()
df['month']=df['date'].dt.month_name()
df

,trip_id,date,pickup_location,drop_location,distance_km,fare_amount,payment_type,driver_rating,hour,day,month
0,1,2024-01-01,Chennai Airport,T Nagar,12.5,350,UPI,4.8,0,Monday,January
1,2,2024-01-01,T Nagar,OMR,8.2,210,Cash,4.5,0,Monday,January
2,3,2024-01-01,Velachery,Guindy,5.4,150,UPI,5.0,0,Monday,January
3,4,2024-01-01,OMR,Navalur,14.0,290,Card,4.6,0,Monday,January
4,5,2024-01-02,Tambaram,Airport,10.1,300,UPI,4.2,0,Tuesday,January
5,6,2024-01-02,Adyar,Velachery,11.3,250,Cash,4.3,0,Tuesday,January
6,7,2024-01-02,Perungudi,Chennai Airport,18.2,520,Card,4.7,0,Tuesday,January
7,8,2024-01-02,Anna Nagar,T Nagar,7.5,180,UPI,4.4,0,Tuesday,January
8,9,2024-01-03,Guindy,OMR,13.4,360,Cash,4.1,0,Wednesday,January
9,10,2024-01-03,T Nagar,Adyar,9.0,220,UPI,4.9,0,Wednesday,January
10,11,2024-01-03,Navalur,Guindy,15.6,450,UPI,4.8,0,Wednesday,January
11,12,2024-01-03,Kodambakkam,ECR,6.3,160,Card,4.5,0,Wednesday,January
12,13,2024-01-04,Chengalpattu,Tambaram,41.2,900,UPI,4.0,0,Thursday,January
13,14,2024-01-04,Velachery,Ann Nagar,4.8,140,Cash,5.0,0,Thursday,January
14,15,2024-01-04,Teynampet,OMR,8.5,200,Card,4.6,0,Thursday,January
15,16,2024-01-04,Thiruvanmiyur,Perungudi,6.7,180,UPI,4.3,0,Thursday,January
16,17,2024-01-05,ECR,T Nagar,22.0,600,UPI,4.8,0,Friday,January
17,18,2024-01-05,Kilpauk,Airport,11.1,260,Cash,4.5,0,Friday,January
18,19,2024-01-05,MMDA,Ambattur,16.5,430,UPI,4.7,0,Friday,January
19,20,2024-01-05,Madhavaram,Perambur,12.2,310,Card,4.4,0,Friday,January
20,21,2024-01-06,Koyambedu,Guindy,9.8,230,Cash,4.2,0,Saturday,January
21,22,2024-01-06,Porur,Thoraipakkam,14.7,320,UPI,4.1,0,Saturday,January
22,23,2024-01-06,Ambattur,Velachery,7.9,190,Card,4.9,0,Saturday,January
23,24,2024-01-06,Pallavaram,MMDA,10.4,275,UPI,4.6,0,Saturday,January
24,25,2024-01-07,T Nagar,OMR,13.6,330,Cash,4.8,0,Sunday,January

In [8]:
df_sorted=df.sort_values(by='hour',ascending=True)
df_sorted

,trip_id,date,pickup_location,drop_location,distance_km,fare_amount,payment_type,driver_rating,hour,day,month
0,1,2024-01-01,Chennai Airport,T Nagar,12.5,350,UPI,4.8,0,Monday,January
1,2,2024-01-01,T Nagar,OMR,8.2,210,Cash,4.5,0,Monday,January
2,3,2024-01-01,Velachery,Guindy,5.4,150,UPI,5.0,0,Monday,January
3,4,2024-01-01,OMR,Navalur,14.0,290,Card,4.6,0,Monday,January
4,5,2024-01-02,Tambaram,Airport,10.1,300,UPI,4.2,0,Tuesday,January
5,6,2024-01-02,Adyar,Velachery,11.3,250,Cash,4.3,0,Tuesday,January
6,7,2024-01-02,Perungudi,Chennai Airport,18.2,520,Card,4.7,0,Tuesday,January
7,8,2024-01-02,Anna Nagar,T Nagar,7.5,180,UPI,4.4,0,Tuesday,January
8,9,2024-01-03,Guindy,OMR,13.4,360,Cash,4.1,0,Wednesday,January
9,10,2024-01-03,T Nagar,Adyar,9.0,220,UPI,4.9,0,Wednesday,January
10,11,2024-01-03,Navalur,Guindy,15.6,450,UPI,4.8,0,Wednesday,January
11,12,2024-01-03,Kodambakkam,ECR,6.3,160,Card,4.5,0,Wednesday,January
12,13,2024-01-04,Chengalpattu,Tambaram,41.2,900,UPI,4.0,0,Thursday,January
13,14,2024-01-04,Velachery,Ann Nagar,4.8,140,Cash,5.0,0,Thursday,January
14,15,2024-01-04,Teynampet,OMR,8.5,200,Card,4.6,0,Thursday,January
15,16,2024-01-04,Thiruvanmiyur,Perungudi,6.7,180,UPI,4.3,0,Thursday,January
16,17,2024-01-05,ECR,T Nagar,22.0,600,UPI,4.8,0,Friday,January
17,18,2024-01-05,Kilpauk,Airport,11.1,260,Cash,4.5,0,Friday,January
18,19,2024-01-05,MMDA,Ambattur,16.5,430,UPI,4.7,0,Friday,January
19,20,2024-01-05,Madhavaram,Perambur,12.2,310,Card,4.4,0,Friday,January
20,21,2024-01-06,Koyambedu,Guindy,9.8,230,Cash,4.2,0,Saturday,January
21,22,2024-01-06,Porur,Thoraipakkam,14.7,320,UPI,4.1,0,Saturday,January
22,23,2024-01-06,Ambattur,Velachery,7.9,190,Card,4.9,0,Saturday,January
23,24,2024-01-06,Pallavaram,MMDA,10.4,275,UPI,4.6,0,Saturday,January
24,25,2024-01-07,T Nagar,OMR,13.6,330,Cash,4.8,0,Sunday,January

In [9]:
df.sort_values(by='distance_km', ascending=True)

,trip_id,date,pickup_location,drop_location,distance_km,fare_amount,payment_type,driver_rating,hour,day,month
13,14,2024-01-04,Velachery,Ann Nagar,4.8,140,Cash,5.0,0,Thursday,January
2,3,2024-01-01,Velachery,Guindy,5.4,150,UPI,5.0,0,Monday,January
11,12,2024-01-03,Kodambakkam,ECR,6.3,160,Card,4.5,0,Wednesday,January
15,16,2024-01-04,Thiruvanmiyur,Perungudi,6.7,180,UPI,4.3,0,Thursday,January
7,8,2024-01-02,Anna Nagar,T Nagar,7.5,180,UPI,4.4,0,Tuesday,January
22,23,2024-01-06,Ambattur,Velachery,7.9,190,Card,4.9,0,Saturday,January
1,2,2024-01-01,T Nagar,OMR,8.2,210,Cash,4.5,0,Monday,January
14,15,2024-01-04,Teynampet,OMR,8.5,200,Card,4.6,0,Thursday,January
9,10,2024-01-03,T Nagar,Adyar,9.0,220,UPI,4.9,0,Wednesday,January
20,21,2024-01-06,Koyambedu,Guindy,9.8,230,Cash,4.2,0,Saturday,January
4,5,2024-01-02,Tambaram,Airport,10.1,300,UPI,4.2,0,Tuesday,January
23,24,2024-01-06,Pallavaram,MMDA,10.4,275,UPI,4.6,0,Saturday,January
17,18,2024-01-05,Kilpauk,Airport,11.1,260,Cash,4.5,0,Friday,January
5,6,2024-01-02,Adyar,Velachery,11.3,250,Cash,4.3,0,Tuesday,January
19,20,2024-01-05,Madhavaram,Perambur,12.2,310,Card,4.4,0,Friday,January
0,1,2024-01-01,Chennai Airport,T Nagar,12.5,350,UPI,4.8,0,Monday,January
8,9,2024-01-03,Guindy,OMR,13.4,360,Cash,4.1,0,Wednesday,January
24,25,2024-01-07,T Nagar,OMR,13.6,330,Cash,4.8,0,Sunday,January
3,4,2024-01-01,OMR,Navalur,14.0,290,Card,4.6,0,Monday,January
21,22,2024-01-06,Porur,Thoraipakkam,14.7,320,UPI,4.1,0,Saturday,January
10,11,2024-01-03,Navalur,Guindy,15.6,450,UPI,4.8,0,Wednesday,January
18,19,2024-01-05,MMDA,Ambattur,16.5,430,UPI,4.7,0,Friday,January
6,7,2024-01-02,Perungudi,Chennai Airport,18.2,520,Card,4.7,0,Tuesday,January
16,17,2024-01-05,ECR,T Nagar,22.0,600,UPI,4.8,0,Friday,January
12,13,2024-01-04,Chengalpattu,Tambaram,41.2,900,UPI,4.0,0,Thursday,January

In [10]:
df.sort_values(by='fare_amount', ascending=False)

,trip_id,date,pickup_location,drop_location,distance_km,fare_amount,payment_type,driver_rating,hour,day,month
12,13,2024-01-04,Chengalpattu,Tambaram,41.2,900,UPI,4.0,0,Thursday,January
16,17,2024-01-05,ECR,T Nagar,22.0,600,UPI,4.8,0,Friday,January
6,7,2024-01-02,Perungudi,Chennai Airport,18.2,520,Card,4.7,0,Tuesday,January
10,11,2024-01-03,Navalur,Guindy,15.6,450,UPI,4.8,0,Wednesday,January
18,19,2024-01-05,MMDA,Ambattur,16.5,430,UPI,4.7,0,Friday,January
8,9,2024-01-03,Guindy,OMR,13.4,360,Cash,4.1,0,Wednesday,January
0,1,2024-01-01,Chennai Airport,T Nagar,12.5,350,UPI,4.8,0,Monday,January
24,25,2024-01-07,T Nagar,OMR,13.6,330,Cash,4.8,0,Sunday,January
21,22,2024-01-06,Porur,Thoraipakkam,14.7,320,UPI,4.1,0,Saturday,January
19,20,2024-01-05,Madhavaram,Perambur,12.2,310,Card,4.4,0,Friday,January
4,5,2024-01-02,Tambaram,Airport,10.1,300,UPI,4.2,0,Tuesday,January
3,4,2024-01-01,OMR,Navalur,14.0,290,Card,4.6,0,Monday,January
23,24,2024-01-06,Pallavaram,MMDA,10.4,275,UPI,4.6,0,Saturday,January
17,18,2024-01-05,Kilpauk,Airport,11.1,260,Cash,4.5,0,Friday,January
5,6,2024-01-02,Adyar,Velachery,11.3,250,Cash,4.3,0,Tuesday,January
20,21,2024-01-06,Koyambedu,Guindy,9.8,230,Cash,4.2,0,Saturday,January
9,10,2024-01-03,T Nagar,Adyar,9.0,220,UPI,4.9,0,Wednesday,January
1,2,2024-01-01,T Nagar,OMR,8.2,210,Cash,4.5,0,Monday,January
14,15,2024-01-04,Teynampet,OMR,8.5,200,Card,4.6,0,Thursday,January
22,23,2024-01-06,Ambattur,Velachery,7.9,190,Card,4.9,0,Saturday,January
7,8,2024-01-02,Anna Nagar,T Nagar,7.5,180,UPI,4.4,0,Tuesday,January
15,16,2024-01-04,Thiruvanmiyur,Perungudi,6.7,180,UPI,4.3,0,Thursday,January
11,12,2024-01-03,Kodambakkam,ECR,6.3,160,Card,4.5,0,Wednesday,January
2,3,2024-01-01,Velachery,Guindy,5.4,150,UPI,5.0,0,Monday,January
13,14,2024-01-04,Velachery,Ann Nagar,4.8,140,Cash,5.0,0,Thursday,January

In [11]:
df

,trip_id,date,pickup_location,drop_location,distance_km,fare_amount,payment_type,driver_rating,hour,day,month
0,1,2024-01-01,Chennai Airport,T Nagar,12.5,350,UPI,4.8,0,Monday,January
1,2,2024-01-01,T Nagar,OMR,8.2,210,Cash,4.5,0,Monday,January
2,3,2024-01-01,Velachery,Guindy,5.4,150,UPI,5.0,0,Monday,January
3,4,2024-01-01,OMR,Navalur,14.0,290,Card,4.6,0,Monday,January
4,5,2024-01-02,Tambaram,Airport,10.1,300,UPI,4.2,0,Tuesday,January
5,6,2024-01-02,Adyar,Velachery,11.3,250,Cash,4.3,0,Tuesday,January
6,7,2024-01-02,Perungudi,Chennai Airport,18.2,520,Card,4.7,0,Tuesday,January
7,8,2024-01-02,Anna Nagar,T Nagar,7.5,180,UPI,4.4,0,Tuesday,January
8,9,2024-01-03,Guindy,OMR,13.4,360,Cash,4.1,0,Wednesday,January
9,10,2024-01-03,T Nagar,Adyar,9.0,220,UPI,4.9,0,Wednesday,January
10,11,2024-01-03,Navalur,Guindy,15.6,450,UPI,4.8,0,Wednesday,January
11,12,2024-01-03,Kodambakkam,ECR,6.3,160,Card,4.5,0,Wednesday,January
12,13,2024-01-04,Chengalpattu,Tambaram,41.2,900,UPI,4.0,0,Thursday,January
13,14,2024-01-04,Velachery,Ann Nagar,4.8,140,Cash,5.0,0,Thursday,January
14,15,2024-01-04,Teynampet,OMR,8.5,200,Card,4.6,0,Thursday,January
15,16,2024-01-04,Thiruvanmiyur,Perungudi,6.7,180,UPI,4.3,0,Thursday,January
16,17,2024-01-05,ECR,T Nagar,22.0,600,UPI,4.8,0,Friday,January
17,18,2024-01-05,Kilpauk,Airport,11.1,260,Cash,4.5,0,Friday,January
18,19,2024-01-05,MMDA,Ambattur,16.5,430,UPI,4.7,0,Friday,January
19,20,2024-01-05,Madhavaram,Perambur,12.2,310,Card,4.4,0,Friday,January
20,21,2024-01-06,Koyambedu,Guindy,9.8,230,Cash,4.2,0,Saturday,January
21,22,2024-01-06,Porur,Thoraipakkam,14.7,320,UPI,4.1,0,Saturday,January
22,23,2024-01-06,Ambattur,Velachery,7.9,190,Card,4.9,0,Saturday,January
23,24,2024-01-06,Pallavaram,MMDA,10.4,275,UPI,4.6,0,Saturday,January
24,25,2024-01-07,T Nagar,OMR,13.6,330,Cash,4.8,0,Sunday,January

In [12]:
df.groupby('hour').size()

hour
0    25
dtype: int64

In [15]:
df.groupby('day').size()

day
Friday       4
Monday       4
Saturday     4
Sunday       1
Thursday     4
Tuesday      4
Wednesday    4
dtype: int64

In [16]:
df.groupby('day')['fare_amount'].mean()

day
Friday       400.00
Monday       250.00
Saturday     253.75
Sunday       330.00
Thursday     355.00
Tuesday      312.50
Wednesday    297.50
Name: fare_amount, dtype: float64

In [18]:
df

,trip_id,date,pickup_location,drop_location,distance_km,fare_amount,payment_type,driver_rating,hour,day,month
0,1,2024-01-01,Chennai Airport,T Nagar,12.5,350,UPI,4.8,0,Monday,January
1,2,2024-01-01,T Nagar,OMR,8.2,210,Cash,4.5,0,Monday,January
2,3,2024-01-01,Velachery,Guindy,5.4,150,UPI,5.0,0,Monday,January
3,4,2024-01-01,OMR,Navalur,14.0,290,Card,4.6,0,Monday,January
4,5,2024-01-02,Tambaram,Airport,10.1,300,UPI,4.2,0,Tuesday,January
5,6,2024-01-02,Adyar,Velachery,11.3,250,Cash,4.3,0,Tuesday,January
6,7,2024-01-02,Perungudi,Chennai Airport,18.2,520,Card,4.7,0,Tuesday,January
7,8,2024-01-02,Anna Nagar,T Nagar,7.5,180,UPI,4.4,0,Tuesday,January
8,9,2024-01-03,Guindy,OMR,13.4,360,Cash,4.1,0,Wednesday,January
9,10,2024-01-03,T Nagar,Adyar,9.0,220,UPI,4.9,0,Wednesday,January
10,11,2024-01-03,Navalur,Guindy,15.6,450,UPI,4.8,0,Wednesday,January
11,12,2024-01-03,Kodambakkam,ECR,6.3,160,Card,4.5,0,Wednesday,January
12,13,2024-01-04,Chengalpattu,Tambaram,41.2,900,UPI,4.0,0,Thursday,January
13,14,2024-01-04,Velachery,Ann Nagar,4.8,140,Cash,5.0,0,Thursday,January
14,15,2024-01-04,Teynampet,OMR,8.5,200,Card,4.6,0,Thursday,January
15,16,2024-01-04,Thiruvanmiyur,Perungudi,6.7,180,UPI,4.3,0,Thursday,January
16,17,2024-01-05,ECR,T Nagar,22.0,600,UPI,4.8,0,Friday,January
17,18,2024-01-05,Kilpauk,Airport,11.1,260,Cash,4.5,0,Friday,January
18,19,2024-01-05,MMDA,Ambattur,16.5,430,UPI,4.7,0,Friday,January
19,20,2024-01-05,Madhavaram,Perambur,12.2,310,Card,4.4,0,Friday,January
20,21,2024-01-06,Koyambedu,Guindy,9.8,230,Cash,4.2,0,Saturday,January
21,22,2024-01-06,Porur,Thoraipakkam,14.7,320,UPI,4.1,0,Saturday,January
22,23,2024-01-06,Ambattur,Velachery,7.9,190,Card,4.9,0,Saturday,January
23,24,2024-01-06,Pallavaram,MMDA,10.4,275,UPI,4.6,0,Saturday,January
24,25,2024-01-07,T Nagar,OMR,13.6,330,Cash,4.8,0,Sunday,January

In [19]:
df_filtered = df[df['drop_location'].isin(['T Nagar', 'OMR'])]
df_filtered

,trip_id,date,pickup_location,drop_location,distance_km,fare_amount,payment_type,driver_rating,hour,day,month
0,1,2024-01-01,Chennai Airport,T Nagar,12.5,350,UPI,4.8,0,Monday,January
1,2,2024-01-01,T Nagar,OMR,8.2,210,Cash,4.5,0,Monday,January
7,8,2024-01-02,Anna Nagar,T Nagar,7.5,180,UPI,4.4,0,Tuesday,January
8,9,2024-01-03,Guindy,OMR,13.4,360,Cash,4.1,0,Wednesday,January
14,15,2024-01-04,Teynampet,OMR,8.5,200,Card,4.6,0,Thursday,January
16,17,2024-01-05,ECR,T Nagar,22.0,600,UPI,4.8,0,Friday,January
24,25,2024-01-07,T Nagar,OMR,13.6,330,Cash,4.8,0,Sunday,January

In [21]:
df.to_csv("uber_clean.csv", index=False)